//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenueDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public int VenueId { get; set; }
        public string VenueName { get; set; }
        public double TicketPrice { get; set; }
        public int TicketQuantity { get; set; }
        public double OrderValue { get; set; }
        public string Notes { get; set; }
        public string ShippingOption { get; set; }
    }
}
